# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

source 'https://github.com/CocoaPods/Specs.git'	# 公共仓库
source 'https://github.com/lionsom/LXSpecs.git'	# 私有仓库

target 'TestPods_OC' do
  # Comment the next line if you don't want to use dynamic frameworks
#  use_frameworks!

  # pod 'OnlyOCDemo'          # 全部引入
  pod 'OnlyOCDemo/FunctionB'  # 分层引入

  pod 'OnlySwiftDemo'
  
  
  # Pods for TestPods_OC

  target 'TestPods_OCTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'TestPods_OCUITests' do
    # Pods for testing
  end

end
